build: off

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: false

environment:
    matrix:
      - PRJ_GEN: "Visual Studio 12 2013 Win64"
        BDIR: msvc2013
      - PRJ_GEN: "Visual Studio 14 2015 Win64"
        BDIR: msvc2015

build_script:
    - mkdir build.%BDIR% && cd build.%BDIR%
    - cmake .. -G"%PRJ_GEN%"
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%
    - cmake --build . --config Release --target install
    - ctest -V --output-on-failure -C Release
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/limix/hcephes/master/install.bat', 'install.bat')" && install.bat

test_script:
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\hcephes.lib exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\bin\hcephes.dll exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\lib\hcephes_static.lib exit 1
    - if NOT exist %APPVEYOR_BUILD_FOLDER%\include\hcephes.h exit 1
